[theme]
primaryColor = "#E0EC05"       # Cor principal (elementos interativos como botões)
backgroundColor = "#000000"    # Cor de fundo da página
secondaryBackgroundColor = "#11979E"  # Fundo secundário (para widgets e containers)
textColor = "#FFFFFF"          # Cor do texto principal
font = "sans serif"             # Fonte a ser utilizada
